# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('address_street', models.CharField(max_length=20)),
                ('address_city', models.CharField(max_length=20)),
                ('address_state', models.CharField(max_length=2)),
                ('address_zip', models.CharField(max_length=10)),
                ('account_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPurityReport',
            fields=[
                ('report_number', models.AutoField(primary_key=True, serialize=False)),
                ('water_condition', models.CharField(max_length=20)),
                ('virus_ppm', models.IntegerField()),
                ('contaminant_ppm', models.IntegerField()),
                ('report_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSourceReport',
            fields=[
                ('report_number', models.AutoField(primary_key=True, serialize=False)),
                ('water_type', models.CharField(max_length=20)),
                ('water_condition', models.CharField(max_length=20)),
                ('water_location', models.CharField(max_length=50, unique=True)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('reporter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean_water_crowdsourcing.Account')),
            ],
        ),
        migrations.AddField(
            model_name='waterpurityreport',
            name='water_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean_water_crowdsourcing.WaterSourceReport', to_field='water_location'),
        ),
    ]
